version:             "3"
services:
  ethereum:
     build:          ./ethereum-docker
     container_name: stellar-ethereum
     command:        --fast --cache=512 --rinkeby --rpc --rpcaddr 0.0.0.0
     volumes:
       - ~/stellar/ethereum:/root
     restart:        unless-stopped
     ports:
       - "8545:8545"
       - "30303:30303"
       - "30303:30303/udp"
       - "30304:30304/udp"
